- name: Default setup for cloud debian/ubuntu instances
  hosts: all
  connection: ssh
  gather_facts: yes
  roles:
    - role: "roles/configure-vim"
    - role: "roles/configure-docker"
    - role: "roles/configure-tmux"