---
  - name: set config file tmux
  # take from templates .tmux.config
    become: yes
    ansible.builtin.copy:
      src: "{{ role_path }}/files/tmux.conf"
      dest: "/home/{{ ik_ssh_user}}/.tmux.conf"
      owner: root
      group: root
      mode: 0644
    tags: set-config-file-tmux

