---
  - name: set config file vim
    become: yes
    ansible.builtin.copy:
      src: "{{ role_path }}/files/vimrc"
      dest: "{{ ansible_env.HOME }}/.vimrc"
      owner: root
      group: root
      mode: 0644
    tags: set-config-file-vim